server:
    port: 3170  # 启动端口
    servlet:
        context-path: /api/xingz-cm
spring:
    datasource:
        # mysql
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: wwq5714806
        url: jdbc:mysql://localhost:3306/xingz_cm
    data:
        # redis
        redis:
            database: 0
            host: localhost
            port: 6379
            password: 123456
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
        db-config:
            logic-delete-field: isDeleted
            logic-delete-value: "1"
            logic-not-delete-value: "0"
aliyun:
    # 阿里云短信服务
    sms:
        accessKeyId: LTAI5t5pwZsyfad23GLkdXxe
        accessKeySecret: ecNSw2F78txmWAPUzP9yU0joVYLg9h
    # 阿里云oss对象存储服务
    oss:
        accessKeyId: LTAI5tJ9K46qWUoT9i66wcGD
        accessKeySecret: G4PEXxbZkWNGzHbdIzNfH41osLLTeJ
        endpoint: oss-cn-beijing.aliyuncs.com
        bucketName: xzwz-cm.oss-cn-beijing.aliyuncs.com
## springdoc-openapi项目配置
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        tags-sorter: alpha
        operations-sorter: alpha
    api-docs:
        path: /v3/api-docs
    group-configs:
        -   group: 'default'
            paths-to-match: '/**'
            packages-to-scan: top.kkuily.xingbackend.web.controller



