server:
    port: 3170  # 启动端口
    servlet:
        context-path: /api/xingz-cm
jasypt:
    encryptor:
        password: ${自定义}
spring:
    main:
        # bean 懒加载
        lazy-initialization: true
    datasource:
        # mysql
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ENC(${自定义})
        password: ENC(${自定义})
        url: jdbc:mysql://localhost:3306/xingz_cm
    data:
        # redis
        redis:
            database: 0
            host: localhost
            port: 6379
            password: 123456
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
aliyun:
    # 阿里云短信服务
    sms:
        accessKeyId: ENC(${自定义})
        accessKeySecret: ENC(${自定义})
    # 阿里云oss对象存储服务
    oss:
        endpoint: https://oss-cn-beijing.aliyuncs.com
        accessKeyId: ENC(${自定义})
        accessKeySecret: ENC(${自定义})
        bucketName: xzwz-cm
## springdoc-openapi项目配置
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        tags-sorter: alpha
        operations-sorter: alpha
    api-docs:
        path: /v3/api-docs
    group-configs:
        -   group: 'default'
            paths-to-match: '/**'
            packages-to-scan: top.kkuily.xingbackend.web.controller
