server:
    port: 3170  # 启动端口
    servlet:
        context-path: /api/xingz-cm
jasypt:
    encryptor:
        password: 123456
spring:
    main:
        # bean 懒加载
        lazy-initialization: true
    datasource:
        # mysql
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ENC(uurQNy+AGi1iegkCGsPI3e3PTjeukiEWy0s0ckTqEJmnhFycuR2FBSQrrcoBWnnm)
        password: ENC(j/ug1ZxdpK7WkJL0kMwUYEroBvsI/fNlw4pqPEryqiM4FsqqjuuVThDhThYqsTVQ)
        url: jdbc:mysql://localhost:3306/xingz_cm
    data:
        # redis
        redis:
            database: 0
            host: localhost
            port: 6379
            password: 123456
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
aliyun:
    # 阿里云短信服务
    sms:
        accessKeyId: ENC(tHoUuFsmy4UA8dahCWIO8NmD+9RHPQFbdnrWWHgI3JdXYebFGcmNjhbYpdFvwv8EJxxhxp7Bfwy8IeNXD5L9uA==|)
        accessKeySecret: ENC(OxwCYphe5PKjdXc5yqjewgGAatSfxYi+NC+7ViG1DUUEvJ/UgegSlnqEwGuSbeix6ohWpcs27We7TxGmI8FiVw==|)
    # 阿里云oss对象存储服务
    oss:
        endpoint: https://oss-cn-beijing.aliyuncs.com
        accessKeyId: ENC(Vc6lEhyWTUncfWm9KM1BgCUJDJdHXvlDjqCcqo1fqfrZ1fFy9gxcYyVjP+UglDPSz7Mzp2vEjm+7jo9ahfr0fQ==|)
        accessKeySecret: ENC(G3OxWaToOkYYF1IgUfuRIf9Xxx9lyGCwAMeW7YJcImvFNmWvIWgANfx79esZ/WzZlguigQSBHOtFvgJN9whxBw==|)
        bucketName: xzwz-cm
## springdoc-openapi项目配置
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        tags-sorter: alpha
        operations-sorter: alpha
    api-docs:
        path: /v3/api-docs
    group-configs:
        -   group: 'default'
            paths-to-match: '/**'
            packages-to-scan: top.kkuily.xingbackend.web.controller
